// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ay7Z0t0BuTJUcgMY8XsxlWSGsx83n1I',
    appId: '1:949246123139:web:615a8084a71b778df88fb6',
    messagingSenderId: '949246123139',
    projectId: 'emoney-radenz',
    authDomain: 'emoney-radenz.firebaseapp.com',
    storageBucket: 'emoney-radenz.firebasestorage.app',
    measurementId: 'G-T9TQ6CV2T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJsn97RcgfFzNvm0wxHy6ZGN6YlhsDTA',
    appId: '1:949246123139:android:42c3e8a62c2b800cf88fb6',
    messagingSenderId: '949246123139',
    projectId: 'emoney-radenz',
    storageBucket: 'emoney-radenz.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ay7Z0t0BuTJUcgMY8XsxlWSGsx83n1I',
    appId: '1:949246123139:web:8c02b708de0a8ae3f88fb6',
    messagingSenderId: '949246123139',
    projectId: 'emoney-radenz',
    authDomain: 'emoney-radenz.firebaseapp.com',
    storageBucket: 'emoney-radenz.firebasestorage.app',
    measurementId: 'G-GP0RFGC6RV',
  );
}
